[package]
name = "client"
version = "0.1.0"
edition = "2021"

[dependencies]
winapi = { version = "0.3.9", features = ["synchapi", "errhandlingapi", "dxgi1_2", "winerror", "wingdi", "winuser", "securitybaseapi", "winuser","wincon","shellapi"] }
screenshots = "0.8.10"
sysinfo = "0.30.10"
common = { path = "../common" }
rand = "0.8.5"
rmp-serde = "1.2.0"
rand_chacha = "0.3.1"
rsa = "0.5.0"
lazy_static = "1.4.0"
once_cell = "1.19.0"
tokio = { version = "1.20.1", features = ["rt", "full"] }
bytes = "1.1"
net2 = "0.2.39"
wmi = "0.17.0"
windows = { version = "0.61", features = ["Win32_System_Diagnostics_Debug", "Win32_System_Wmi", "Win32_System_Com"] }
serde = { version = "1.0", features = ["derive"] }

[profile.release]
lto = true
opt-level = 'z'
strip = true
codegen-units = 1
panic = "abort"