[workspace]
members = ["server/src-tauri", "client", "common", "plugins/*"]
resolver = "2"

[profile.release]
lto = true
codegen-units = 1

# [profile.release.package.server]
# debug = true
# debug-assertions = true